[package]
name = "jav-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# glob = "0.3.0"
crossterm = "0.25.0"
regex = "1.6.0"
walkdir = "2.3.2"
